# Generated by Django 5.0.6 on 2024-07-14 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="date",
            field=models.DateField(default=datetime.date(2024, 7, 14)),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.TimeField(default=datetime.time(20, 19, 57, 385648)),
        ),
    ]
