# Generated by Django 5.0.6 on 2024-07-15 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_alter_reservation_date_alter_reservation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="date",
            field=models.DateField(default=datetime.date(2024, 7, 15)),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.TimeField(default=datetime.time(23, 28, 17, 281463)),
        ),
    ]
