# Generated by Django 5.0.6 on 2024-07-15 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_alter_reservation_date_alter_reservation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.TimeField(default=datetime.time(23, 29, 56, 759716)),
        ),
    ]
