# Generated by Django 5.0.6 on 2024-07-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_alter_reservation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="time",
            field=models.TimeField(auto_now_add=True),
        ),
    ]
