# Generated by Django 5.0.6 on 2024-07-16 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0006_alter_reservation_date_alter_reservation_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.TimeField(verbose_name=datetime.time(1, 31, 23, 87379)),
        ),
        migrations.AlterField(
            model_name="room",
            name="time",
            field=models.TimeField(verbose_name=datetime.time(1, 31, 23, 87252)),
        ),
    ]
