# Generated by Django 5.0.6 on 2024-07-16 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0007_alter_reservation_time_alter_room_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.TimeField(verbose_name=datetime.time(2, 24, 59, 834928)),
        ),
        migrations.AlterField(
            model_name="room",
            name="time",
            field=models.TimeField(verbose_name=datetime.time(2, 24, 59, 834768)),
        ),
    ]
