# Generated by Django 5.0.6 on 2024-07-16 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0008_alter_reservation_time_alter_room_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.TimeField(verbose_name=datetime.time(2, 29, 8, 797079)),
        ),
        migrations.AlterField(
            model_name="room",
            name="time",
            field=models.TimeField(verbose_name=datetime.time(2, 29, 8, 796930)),
        ),
    ]
