# Generated by Django 5.0.6 on 2024-07-20 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0010_alter_reservation_time_alter_room_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="date",
            field=models.DateField(verbose_name=datetime.date(2024, 7, 20)),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.TimeField(verbose_name=datetime.time(8, 6, 25, 474141)),
        ),
        migrations.AlterField(
            model_name="room",
            name="date",
            field=models.DateField(verbose_name=datetime.date(2024, 7, 20)),
        ),
        migrations.AlterField(
            model_name="room",
            name="time",
            field=models.TimeField(verbose_name=datetime.time(8, 6, 25, 474010)),
        ),
    ]
