# Generated by Django 5.0.6 on 2024-07-21 07:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0011_alter_reservation_date_alter_reservation_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="available_family_rooms",
            new_name="available_band_rooms",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="date",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="time",
        ),
        migrations.RemoveField(
            model_name="room",
            name="available_double_rooms",
        ),
        migrations.RemoveField(
            model_name="room",
            name="available_single_rooms",
        ),
        migrations.AddField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="available_duet_rooms",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="room",
            name="available_solo_rooms",
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="room",
            name="date",
            field=models.DateField(verbose_name=datetime.date(2024, 7, 21)),
        ),
        migrations.AlterField(
            model_name="room",
            name="time",
            field=models.TimeField(verbose_name=datetime.time(7, 33, 45, 398638)),
        ),
    ]
