# Generated by Django 5.0.6 on 2024-07-21 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "booking",
            "0012_rename_available_family_rooms_room_available_band_rooms_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="time",
            field=models.TimeField(verbose_name=datetime.time(8, 13, 57, 741215)),
        ),
    ]
