# Generated by Django 5.0.6 on 2024-07-21 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0013_alter_room_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("Solo", "Solo"),
                    ("RoomType2", "Duet"),
                    ("RoomType3", "Band"),
                ],
                default="Solo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="time",
            field=models.TimeField(verbose_name=datetime.time(21, 5, 31, 741548)),
        ),
    ]
