# Generated by Django 5.0.6 on 2024-07-22 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0014_reservation_room_type_alter_room_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="date",
            field=models.DateField(verbose_name=datetime.date(2024, 7, 22)),
        ),
        migrations.AlterField(
            model_name="room",
            name="time",
            field=models.TimeField(verbose_name=datetime.time(1, 0, 59, 740723)),
        ),
    ]
